// Todo App Frontend Configuration
// This file is automatically generated by run.sh
window.ENV = {
  // API Configuration - Set by run.sh script
  API_BASE_URL: "http://localhost:8000",
  
  // Environment
  ENVIRONMENT: "development",
  
  // Initialize configuration
  async init() {
    try {
      console.log('🌐 Initializing Todo App Frontend...');
      console.log('📡 Backend API URL:', this.API_BASE_URL);
      
      // Test backend connection
      const response = await fetch(`${this.API_BASE_URL}/health`);
      if (response.ok) {
        console.log('✅ Backend connection successful');
        const healthData = await response.json();
        console.log('🔧 Backend Status:', healthData);
      } else {
        console.warn('⚠️  Backend health check failed');
        console.warn('📋 Make sure backend is running on:', this.API_BASE_URL);
      }
    } catch (error) {
      console.warn('⚠️  Could not reach backend:', error.message);
      console.warn('📋 Make sure backend is running on:', this.API_BASE_URL);
      console.warn('🔧 Run ./run.sh to reconfigure if needed');
    }
  },

  // Get API URL
  getEnvApiUrl() {
    return this.API_BASE_URL;
  }
};

// Initialize configuration when the script loads
window.ENV.init();
